# Generated by Django 4.2.1 on 2023-06-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='नाम')),
                ('phone', models.CharField(max_length=20, verbose_name='फ़ोन')),
                ('address', models.CharField(max_length=200, verbose_name='पता')),
                ('gav', models.CharField(max_length=100, verbose_name='गांव')),
                ('problem', models.TextField(verbose_name='समस्या')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_solved', models.BooleanField(default=False)),
                ('is_spam', models.BooleanField(default=False)),
            ],
        ),
    ]
